/*
 * BizObs LoadRunner Journey Template
 * 
 * Dynatrace Integration with Request Tagging:
 * - LSN (Load Script Name): Identifies the LoadRunner script
 * - TSN (Test Step Name): Identifies individual test steps  
 * - LTN (Load Test Name): Identifies the test execution run
 * 
 * Generated by BizObs Business Observability Generator
 */

#include "web_api.h"
#include "lrun.h"

// Global variables for Dynatrace tagging
char LSN[256] = "{{SCRIPT_NAME}}";          // Load Script Name
char LTN[256] = "{{TEST_NAME}}";            // Load Test Name  
char TSN[256] = "{{STEP_NAME}}";            // Test Step Name (changes per step)
char dt_header[1024];                       // Dynatrace header buffer
char company_name[128] = "{{COMPANY_NAME}}";
char base_url[256] = "{{BASE_URL}}";

// Journey configuration
int journey_steps = {{STEP_COUNT}};
int think_time_ms = {{THINK_TIME}};
int error_simulation = {{ERROR_SIMULATION}};

// Performance counters
double response_time;
int transaction_status;

Action()
{
    char step_name[256];
    char endpoint_url[512];
    char request_body[2048];
    int step_duration;
    
    // Initialize test execution
    lr_start_transaction("Journey_Initialization");
    
    // Set Dynatrace headers for load test identification
    sprintf(dt_header, "VU: %d; SI: %s; TSN: Journey_Start; LSN: %s; LTN: %s", 
            lr_get_vuser_id(), lr_get_session_id(), LSN, LTN);
    
    web_add_header("X-dynaTrace", dt_header);
    web_add_header("X-LoadRunner-Company", company_name);
    
    lr_end_transaction("Journey_Initialization", LR_PASS);
    
    // Journey Steps Loop
{{JOURNEY_STEPS}}
    
    // Final transaction summary
    lr_start_transaction("Journey_Complete");
    
    sprintf(dt_header, "VU: %d; SI: %s; TSN: Journey_Complete; LSN: %s; LTN: %s", 
            lr_get_vuser_id(), lr_get_session_id(), LSN, LTN);
    web_add_header("X-dynaTrace", dt_header);
    
    // Send journey completion event
    sprintf(request_body, 
        "{"
        "\"eventType\": \"JOURNEY_COMPLETE\","
        "\"companyName\": \"%s\","
        "\"testName\": \"%s\","
        "\"scriptName\": \"%s\","
        "\"vuserId\": %d,"
        "\"sessionId\": \"%s\","
        "\"timestamp\": \"{{TIMESTAMP}}\","
        "\"totalSteps\": %d"
        "}",
        company_name, LTN, LSN, lr_get_vuser_id(), lr_get_session_id(), journey_steps
    );
    
    web_custom_request("Journey_Summary",
        "URL={base_url}/api/journey-complete",
        "Method=POST",
        "Resource=0",
        "RecContentType=application/json",
        "Referer=",
        "Snapshot=t1.inf",
        "Mode=HTTP",
        "Body={request_body}",
        LAST);
    
    lr_end_transaction("Journey_Complete", LR_PASS);
    
    return 0;
}

// Individual step template function
int execute_journey_step(char* step_name, char* endpoint, char* method, char* body, int duration)
{
    char transaction_name[256];
    char full_url[512];
    
    // Create transaction name
    sprintf(transaction_name, "Step_%s", step_name);
    
    lr_start_transaction(transaction_name);
    
    // Update TSN for this specific step
    sprintf(dt_header, "VU: %d; SI: %s; TSN: %s; LSN: %s; LTN: %s", 
            lr_get_vuser_id(), lr_get_session_id(), step_name, LSN, LTN);
    
    web_add_header("X-dynaTrace", dt_header);
    web_add_header("X-LoadRunner-Step", step_name);
    web_add_header("X-LoadRunner-Duration", lr_eval_string("{duration}"));
    
    // Build full URL
    sprintf(full_url, "%s%s", base_url, endpoint);
    
    // Execute the request based on method
    if (strcmp(method, "POST") == 0) {
        web_custom_request(step_name,
            "URL={full_url}",
            "Method=POST",
            "Resource=0",
            "RecContentType=application/json",
            "Referer=",
            "Snapshot=t1.inf",
            "Mode=HTTP",
            "Body={body}",
            LAST);
    } else {
        web_url(step_name, "URL={full_url}", "Resource=0", "RecContentType=text/html", "Referer=", "Snapshot=t1.inf", "Mode=HTTP", LAST);
    }
    
    // Think time based on step duration
    lr_think_time(duration);
    
    // Check for errors if error simulation is enabled
    if (error_simulation && (rand() % 100) < 5) {  // 5% error rate
        lr_end_transaction(transaction_name, LR_FAIL);
        lr_error_message("Simulated error in step: %s", step_name);
        return LR_FAIL;
    }
    
    lr_end_transaction(transaction_name, LR_PASS);
    return LR_PASS;
}

// Error handling function
int handle_step_error(char* step_name, int error_code)
{
    char error_transaction[256];
    sprintf(error_transaction, "Error_%s", step_name);
    
    lr_start_transaction(error_transaction);
    
    // Update headers for error tracking
    sprintf(dt_header, "VU: %d; SI: %s; TSN: Error_%s; LSN: %s; LTN: %s; ErrorCode: %d", 
            lr_get_vuser_id(), lr_get_session_id(), step_name, LSN, LTN, error_code);
    
    web_add_header("X-dynaTrace", dt_header);
    web_add_header("X-LoadRunner-Error", "true");
    
    lr_end_transaction(error_transaction, LR_FAIL);
    
    return 0;
}